version: '3.7'
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - HOST=http://localhost
      - MONGO_URI=mongodb+srv://admin:8BjImyNUMKVeQFJW@rentalcarbooking.b263jat.mongodb.net/RentalCarBooking?retryWrites=true&w=majority&appName=RentalCarBooking
      - JWT_SECRET=asdfghjkl;;lkjhgfdsa
      - JWT_EXPIRE=30d
      - JWT_COOKIE_EXPIRE=30
      - GOOGLE_MAPS_API_KEY=AIzaSyD2bq4KbruP-Mz5AZK5AY8nd9gmNNbasDM
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXTAUTH_SECRET=Ey7nTKnggBc0bRN8WUjyShw2qzOZ6KW4fUyqcKBePxY=
      - NEXTAUTH_URL=http://localhost:3000
      - FRONTEND_URL=http://localhost:3000
      - BACKEND_URL=http://localhost:5000
      - STRIPE_SECRET_KEY=sk_test_51P5X3fP2DLxtaTIwvwA3CRQDO4UnSEB8emQbLEnZS9wNX35AKfl4BXpQj4fsIdA1ROlkhPvmHlq5szyxRSryNFiN00nXztp4XF
      - STRIPE_PUBISHABLE_KEY=pk_test_51P5X3fP2DLxtaTIwkpKzZRvvCNSbrzmvKenomunFk3aN0QPptrkMRElVw6snnYcWTf7oBlmpmdCk9hfQidhPyC8U00X7nfgfKn
      - STRIPE_WEBHOOK_SECRET=whsec_11a1c4f2aad42fa784da126828128dfbf10c016c2f159f05224bcb02faa36766
      - NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=dc2cbbsez
      - NEXT_PUBLIC_CLOUDINARY_API_KEY=761198767719618
      - CLOUDINARY_API_SECRET=rRNRT6UB58EEn2Dc4oXuCKctKwg